# check if tests succeed
sudo: required
language: python
python:
  - "3.6"

before_install:
  - sudo apt-get install -y build-essential wget git
  - sudo apt-get install -y python3-pip python3-cffi
  - pip install -U pip setuptools
  - pip install Sphinx
  - pip install sphinx_rtd_theme

install:
  - python setup.py install

script:
  - python setup.py test
  - make html

deploy:
  - provider: pypi
    user: smartshark
    password:
      secure: HJyzZ+VT+S8DMzgxBqzzDX1MOwpQ3em6K0ZcGpePFVthwKl3pbJqIfPcXwjXakmowXJYA2T28InvDpDapTbnDFO/M9fwUR6Ac6uMZjIfPn+paJ2QPHkB37VQXF6SiGla+/e/MfClqKCbLZgLQC5gnyQp8C8Y8/ssAwRq/g5JLcv0IdZC3T5gWDFWKHb2wnD9i04MqJRvIKMcWRP4ksrYkqVf9dNAlGFdGC72qVmklPtEDTuveGsmwMQzY5HgfAPLRKZgWpKu99nBt456Op6Tsq7qQxeNL5o18JBgLB8nYpr2BE5caNZrxsF0JrkWljgaR/n4MsQL899qPeJFgZfAlQ6JW8pJSnPu0SlxxBppETGFmoL4PIxdr7lXBxSFVn5NlwDSZJvnGhLECZHLwVOcznyWB0lhQMQCxyBNfxoW4Hg0rcEUZUDRgdgdfaIsnLBEEWess1O62+bDZXjIsy388MoASUBPqZL16zjmDN1pYY/cLAPwfiBtvPlotERwGP1dctHoYExBtDsk53Veio28lzXEnL4dLiXX4H0BdEeegTzpCYcuPL/R4znU+1tKgcXy3AkpOUr1zvI5pVO8WsTpVIjA76hBgYMamZQpP/ouLk9sjCDRg+Sr/uIovoPl+p9GXvE2ooNvcok0lRFhKtJg/naEwoN6liD+tmdRBxqL+r8=
    on:
      tags: true
  - provider: pages
    github-token: $(TRAVIS_GH_TOKEN}
    local-dir: $TRAVIS_BUILD_DIR/docs/build
    skip_cleanup: true
    on:
      branch: master